"""
YesWeHack Bug Bounty Plugin for ThreatVault
Processes CSV files generated by ywh2csv.py into ThreatVault VAPT format

This plugin is specifically designed to handle the output from ywh2csv.py which exports
YesWeHack bug bounty reports in a standardized CSV format.

Expected CSV format from ywh2csv.py:
    CVE,Risk,Host,Port,Name,Description,Solution,Plugin Output,VPR Score
    #YWH-12345-1,HIGH,example.com,0,Vulnerability Name,...,...,,

Author: ThreatVault Team
"""

import polars as pl


def process(file: bytes, file_type: str) -> pl.DataFrame:
    """
    Process YesWeHack CSV (from ywh2csv.py) to ThreatVault VAPT format

    Args:
        file: Raw CSV file content as bytes (generated by ywh2csv.py)
        file_type: MIME type (expected: "text/csv" or "csv")

    Returns:
        Polars DataFrame with standardized VAPT schema

    Output Schema:
        ["cve", "risk", "host", "port", "name", "description", "remediation", "evidence", "vpr_score"]

    Field Mappings from ywh2csv.py CSV:
        CVE              → cve          (Bug bounty report ID, e.g., #YWH-12345-1)
        Risk             → risk         (Already uppercase: CRITICAL, HIGH, MEDIUM, LOW)
        Host             → host         (Already cleaned hostname)
        Port             → port         (String "0" → Integer 0)
        Name             → name         (Vulnerability title)
        Description      → description  (Already has <br/> tags)
        Solution         → remediation  (Fix instructions)
        Plugin Output    → evidence     (Empty string from ywh2csv.py)
        VPR Score        → vpr_score    (Empty string from ywh2csv.py)

    Data Validations:
        ✅ Port: Converted from String "0" → Integer 0
        ✅ CVE: Bug bounty report IDs preserved (not empty)
        ✅ Risk: Already valid (CRITICAL/HIGH/MEDIUM/LOW)
        ✅ All required fields: No nulls allowed
        ✅ Evidence: Empty string (as per ywh2csv.py output)
        ✅ VPR Score: Empty string (not applicable for bug bounty)
    """
    # Step 1: Validate file type
    # Accept both "text/csv" and "csv" formats
    if file_type not in ["text/csv", "csv"]:
        raise ValueError(f"File type not supported: {file_type}. Expected: text/csv or csv")

    # Step 2: Read CSV and normalize column names
    # ywh2csv.py outputs: CVE,Risk,Host,Port,Name,Description,Solution,Plugin Output,VPR Score
    # Normalize to: cve,risk,host,port,name,description,solution,plugin_output,vpr_score
    df = (
        pl.scan_csv(file)
        .select(pl.all().name.map(lambda x: "_".join(x.lower().split(" "))))
        .collect()
    )

    # Step 3: Validate required columns from ywh2csv.py output
    required_cols = ["cve", "risk", "host", "port", "name", "description", "solution", "plugin_output", "vpr_score"]
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing required columns from ywh2csv.py output: {missing_cols}")

    # Step 4: Filter out invalid risk values (shouldn't happen with ywh2csv.py but safety check)
    df = df.filter(pl.col("risk") != "None")
    df = df.filter(pl.col("risk").is_in(["CRITICAL", "HIGH", "MEDIUM", "LOW"]))

    # Step 5: CRITICAL - Convert Port from String to Integer
    # ywh2csv.py outputs Port as "0" (string), must convert to Integer for ThreatVault
    df = df.with_columns(
        pl.col("port")
        .fill_null("0")              # Safety: Replace any nulls with "0"
        .cast(pl.Utf8)               # Ensure string type first
        .str.replace("^$", "0")      # Replace empty strings with "0"
        .cast(pl.Int64, strict=False) # Convert to Integer type
        .fill_null(0)                # Final safety: any remaining nulls → 0
        .alias("port")
    )

    # Step 6: Handle CVE field - preserve bug bounty report IDs
    # ywh2csv.py populates this with report IDs like #YWH-12345-1
    df = df.with_columns(
        pl.col("cve")
        .fill_null("UNKNOWN")  # Safety: Replace nulls with placeholder
        .cast(pl.Utf8)          # Ensure string type
        .alias("cve")
    )

    # Step 7: Handle VPR Score - already empty from ywh2csv.py
    df = df.with_columns(
        pl.col("vpr_score")
        .fill_null("")        # Convert nulls to empty string
        .cast(pl.Utf8)        # Ensure string type
        .alias("vpr_score")
    )

    # Step 8: Handle Plugin Output (evidence field)
    # ywh2csv.py leaves this empty, but ensure it's never null
    df = df.with_columns(
        pl.col("plugin_output")
        .fill_null("")        # Convert nulls to empty string
        .cast(pl.Utf8)        # Ensure string type
        .alias("plugin_output")
    )

    # Step 9: Newline replacement (already done by ywh2csv.py, but ensure consistency)
    # ywh2csv.py uses format_description() which replaces \n with <br/>
    # This is a safety check in case the CSV has any remaining newlines
    df = df.with_columns(
        pl.col("solution", "description", "plugin_output").str.replace_all(
            "\n", "<br/>"
        )
    )

    # Step 10: Rename columns to ThreatVault schema
    df = df.rename(
        {
            "solution": "remediation",
            "plugin_output": "evidence",
        }
    )

    # Step 11: Final null safety - ensure all required fields are non-null
    df = df.with_columns([
        pl.col("cve").fill_null("UNKNOWN"),              # Bug bounty report ID
        pl.col("risk").fill_null("MEDIUM"),              # Default risk if somehow null
        pl.col("host").fill_null("unknown"),             # Default host if somehow null
        pl.col("port").fill_null(0),                     # Default port (already int)
        pl.col("name").fill_null("Unknown Vulnerability"), # Default name if somehow null
        pl.col("description").fill_null("No description available"),
        pl.col("remediation").fill_null("No remediation available"),
        pl.col("evidence").fill_null(""),                # Evidence can be empty
        pl.col("vpr_score").fill_null(""),               # VPR Score can be empty
    ])

    # Step 12: Select final columns in exact ThreatVault VAPT order
    return df.select([
        "cve",
        "risk",
        "host",
        "port",
        "name",
        "description",
        "remediation",
        "evidence",
        "vpr_score"
    ])
